@echo off
echo Cleaning npm cache...
call npm cache verify
echo Running shadcn create...
npx -y shadcn@latest create nova-app --preset "https://ui.shadcn.com/init?base=radix&style=nova&baseColor=stone&theme=pink&iconLibrary=lucide&font=dm-sans&menuAccent=bold&menuColor=inverted&radius=small&template=next" --template next
